version: '3'
services:
  vuesplash_web:
    container_name: vuesplash_web
    build: .
    volumes:
      - ./web:/var/www/html/vuesplash
    ports:
      - 8081:8081
      - 3000:3000
    command: php artisan serve --host 0.0.0.0 --port 8081
  db:
    restart: always
    image: postgres:11-alpine
    container_name: vuesplash_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5434:5432
    user: postgres
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
      - ./docker/postgres/data:/var/lib/postgresql
